## Data Wrangling for individual City data set

### Steps taken for Data Wrangling

- Reading each individual city data set from AirBNB
- Removal of all unwanted columns from the data set
- Removal of all unwanted fields from each columns
- Converting category type column to Integer for columns like price, bathroom
- Taking care of all missing values in each column
- Renaming of couple of fields
- Merging of Listing data set as well as Calendar data set
- Deriving the new feature i.e Income

### Training City List
- Dallas
- Chicago
- Los Angeles
- Columbus
- Denver
- San Francisco
- New York City
- Seattle
- Portland
- Boston

### Testing City List
- Austin
- San Diego
- Newark

#### Import all libraries

In [1]:
import pandas as pd
import numpy as np

$~$

#### Read the Listing data set and initial check

In [2]:
#Reading the data set
#city_master_data = pd.read_csv("dallas_listings_sep.csv")
#city_master_data = pd.read_csv("newyork_listings_sep.csv")
#city_master_data = pd.read_csv("sfo_listings.csv")
#city_master_data = pd.read_csv("la_listings.csv")
#city_master_data = pd.read_csv("san_diego_listings.csv")
#city_master_data = pd.read_csv("newark_listings.csv")
#city_master_data = pd.read_csv("chicago_listings.csv")
#city_master_data = pd.read_csv("columbus_listings.csv")
#city_master_data = pd.read_csv("denver_listings.csv")
#city_master_data = pd.read_csv("seattle_listings.csv")
#city_master_data = pd.read_csv("portland_listings.csv")
#city_master_data = pd.read_csv("boston_listings.csv")
city_master_data = pd.read_csv("austin_listings.csv")

In [3]:
#Read first 5 records of the data set
city_master_data.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2265,https://www.airbnb.com/rooms/2265,20210914193120,2021-09-15,Zen-East in the Heart of Austin (monthly rental),Zen East is situated in a vibrant & diverse mu...,NaN,https://a0.muscache.com/pictures/4187/52d4f5d0...,2466,https://www.airbnb.com/users/show/2466,...,4.83,4.26,4.35,NaN,f,3,2,1,0,0.36
1,5245,https://www.airbnb.com/rooms/5245,20210914193120,2021-09-15,"Eco friendly, Colorful, Clean, Cozy monthly share",Situated in a vibrant & diverse multicultural ...,NaN,https://a0.muscache.com/pictures/5167505/b33b5...,2466,https://www.airbnb.com/users/show/2466,...,4.40,4.75,4.50,NaN,f,3,2,1,0,0.21
2,5456,https://www.airbnb.com/rooms/5456,20210914193120,2021-09-15,"Walk to 6th, Rainey St and Convention Ctr",Great central location for walking to Convent...,My neighborhood is ideally located if you want...,https://a0.muscache.com/pictures/14084884/b5a3...,8028,https://www.airbnb.com/users/show/8028,...,4.80,4.73,4.78,NaN,f,1,1,0,0,24.96
3,5769,https://www.airbnb.com/rooms/5769,20210914193120,2021-09-15,NW Austin Room,<b>The space</b><br />Looking for a comfortabl...,Quiet neighborhood with lots of trees and good...,https://a0.muscache.com/pictures/23822033/ac94...,8186,https://www.airbnb.com/users/show/8186,...,4.94,4.74,4.92,NaN,f,1,0,1,0,6.08
4,6413,https://www.airbnb.com/rooms/6413,20210914193120,2021-09-15,Gem of a Studio near Downtown,"Great studio apartment, perfect a single perso...",Travis Heights is one of the oldest neighborho...,https://a0.muscache.com/pictures/miso/Hosting-...,13879,https://www.airbnb.com/users/show/13879,...,4.98,4.86,4.94,NaN,t,1,1,0,0,1.28

In [4]:
#Find the number of rows and columns of the data set
city_master_data.shape

(10809, 74)

$~$

#### Removal of unwanted columns

In [5]:
#Print the column names of the data set
city_master_data.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [6]:
#Take a back up the master data set
city_master_data_copy = city_master_data.copy()

In [7]:
#List of the columns needs to be removed
remove_col_names = ['listing_url','scrape_id','last_scraped','name','description','neighborhood_overview',\
                   'picture_url','host_id','host_url','host_name','host_since','host_about','host_response_time',\
                   'host_response_rate','host_acceptance_rate','host_thumbnail_url','host_picture_url',\
                   'host_listings_count','host_verifications','host_has_profile_pic','host_location',\
                   'host_neighbourhood','host_identity_verified','neighbourhood_cleansed',\
                    'neighbourhood_group_cleansed','bathrooms','beds','amenities','minimum_nights',\
                    'maximum_nights','minimum_minimum_nights',\
                   'maximum_minimum_nights', 'minimum_maximum_nights','maximum_maximum_nights',\
                   'calendar_updated', 'has_availability','availability_30', 'availability_60', 'availability_90',\
                   'availability_365','calendar_last_scraped', 'number_of_reviews','number_of_reviews_ltm',\
                    'number_of_reviews_l30d', 'first_review','last_review', 'review_scores_cleanliness',\
                    'review_scores_checkin','review_scores_communication', 'review_scores_location',\
                   'review_scores_value', 'license', 'instant_bookable','calculated_host_listings_count',\
                    'calculated_host_listings_count_entire_homes','calculated_host_listings_count_private_rooms',\
                   'calculated_host_listings_count_shared_rooms', 'reviews_per_month']
city_master_data.drop(remove_col_names, axis=1,inplace=True)

In [8]:
# #Renaming price column to Income
# city_master_data.rename(columns={'price':'income'}, inplace=True)

In [9]:
#Final data set after removoval of all components
city_master_data.head()

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy
0,2265,t,3.0,NaN,30.27752,-97.71377,Entire residential home,Entire home/apt,4,2 baths,2.0,$200.00,7.0,180.0,4.68,4.74
1,5245,t,3.0,NaN,30.27614,-97.71320,Private room in residential home,Private room,2,1 private bath,1.0,$114.00,30.0,90.0,4.57,4.80
2,5456,t,1.0,"Austin, Texas, United States",30.26057,-97.73441,Entire guesthouse,Entire home/apt,3,1 bath,1.0,$104.00,2.0,90.0,4.83,4.87
3,5769,t,1.0,"Austin, Texas, United States",30.45697,-97.78422,Private room in residential home,Private room,2,1 shared bath,1.0,$39.00,1.0,14.0,4.90,4.90
4,6413,t,1.0,"Austin, Texas, United States",30.24885,-97.73587,Entire guesthouse,Entire home/apt,2,1 bath,NaN,$109.00,3.0,1125.0,4.97,4.99

In [10]:
#Final column names from Listing Data set 
city_master_data.columns

Index(['id', 'host_is_superhost', 'host_total_listings_count', 'neighbourhood',
       'latitude', 'longitude', 'property_type', 'room_type', 'accommodates',
       'bathrooms_text', 'bedrooms', 'price', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'review_scores_rating',
       'review_scores_accuracy'],
      dtype='object')

In [11]:
city_master_data.dtypes

id                             int64
host_is_superhost             object
host_total_listings_count    float64
neighbourhood                 object
latitude                     float64
longitude                    float64
property_type                 object
room_type                     object
accommodates                   int64
bathrooms_text                object
bedrooms                     float64
price                         object
minimum_nights_avg_ntm       float64
maximum_nights_avg_ntm       float64
review_scores_rating         float64
review_scores_accuracy       float64
dtype: object

$~$

#### Checking missing values and also if there is any duplicate key ID in the data set

In [12]:
#Check the uniqueness of all ids in the data set
city_master_data[city_master_data.duplicated(['id'], keep=False)]

Empty DataFrame
Columns: [id, host_is_superhost, host_total_listings_count, neighbourhood, latitude, longitude, property_type, room_type, accommodates, bathrooms_text, bedrooms, price, minimum_nights_avg_ntm, maximum_nights_avg_ntm, review_scores_rating, review_scores_accuracy]
Index: []

In [13]:
#Checking missing IDs in the data set
city_master_data['id'].isnull().sum()

0

In [14]:
city_master_data.isnull().sum()

id                              0
host_is_superhost              48
host_total_listings_count      48
neighbourhood                4158
latitude                        0
longitude                       0
property_type                   0
room_type                       0
accommodates                    0
bathrooms_text                 15
bedrooms                      710
price                           0
minimum_nights_avg_ntm          1
maximum_nights_avg_ntm          1
review_scores_rating         2644
review_scores_accuracy       2738
dtype: int64

In [15]:
city_master_data.shape

(10809, 16)

$~$

#### Formatting the price column

In [16]:
#Displaying first 5 records of price column
city_master_data['price'].head()

0    $200.00
1    $114.00
2    $104.00
3     $39.00
4    $109.00
Name: price, dtype: object

In [17]:
#Removing '$' and ',' from the column
city_master_data['price'].replace('\$','', regex=True, inplace=True)
city_master_data['price'].replace('\,','', regex=True, inplace=True)

In [18]:
city_master_data['price'].head()

0    200.00
1    114.00
2    104.00
3     39.00
4    109.00
Name: price, dtype: object

In [19]:
#Coverting the type of price field as float
city_master_data['price'] = city_master_data['price'].astype(float)

$~$

#### Formatting bathrooms_text field and checking missing values

In [20]:
# Displaying the rows when bathrooms_text contains missing values
city_master_data[city_master_data['bathrooms_text'].isnull()].head()

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy
76,247770,f,1.0,NaN,30.30339,-97.68465,Entire residential home,Entire home/apt,5,NaN,3.0,175.0,2.0,75.0,4.00,5.00
89,314152,f,1.0,NaN,30.35672,-97.79621,Entire rental unit,Entire home/apt,4,NaN,2.0,350.0,4.0,14.0,NaN,NaN
111,337125,f,1.0,NaN,30.42035,-97.76685,Private room in residential home,Private room,2,NaN,1.0,80.0,32.0,60.0,4.79,4.76
133,353955,f,1.0,NaN,30.34574,-97.80069,Entire rental unit,Entire home/apt,2,NaN,2.0,225.0,3.0,14.0,4.00,3.00
138,355232,f,1.0,NaN,30.24748,-97.74724,Entire residential home,Entire home/apt,7,NaN,3.0,1000.0,1.0,7.0,5.00,4.67

In [21]:
#Total number of rows having bathrooms_text column contains missing values
city_master_data[city_master_data['bathrooms_text'].isna()].shape

(15, 16)

In [22]:
#Removal of rows containing missing values bathrooms_text column
city_master_data.dropna(subset=['bathrooms_text'],inplace=True)

In [23]:
#Verification of the data set after removal of missing values in review_scores_accuracy column
city_master_data.shape

(10794, 16)

In [24]:
#Displaying some records from bathrooms_text column
city_master_data['bathrooms_text'].head()

0           2 baths
1    1 private bath
2            1 bath
3     1 shared bath
4            1 bath
Name: bathrooms_text, dtype: object

In [25]:
#Checking the values of bathrooms_text field
city_master_data['bathrooms_text'].unique()

array(['2 baths', '1 private bath', '1 bath', '1 shared bath',
       '2.5 baths', '1.5 baths', '3 baths', '3.5 baths', '0 baths',
       '4 baths', '4.5 baths', '2.5 shared baths', '1.5 shared baths',
       'Half-bath', '2 shared baths', '0 shared baths', '5 baths',
       '9 baths', '8 baths', 'Private half-bath', '6.5 baths',
       '5.5 baths', '7 baths', '6 baths', '3 shared baths',
       '4 shared baths', '10.5 baths', '17 baths', '7.5 baths',
       '8.5 baths', '12 baths'], dtype=object)

In [26]:
#Replacing the '\'(single quote) by space
city_master_data['bathrooms_text'].replace('\'','', regex=True, inplace=True)

In [27]:
#removing all the characters from the field
city_master_data['bathrooms_text'] = city_master_data['bathrooms_text'].str.split().str[0]

In [28]:
#Replacing with 0 if the field contains any characters
city_master_data['bathrooms_text'] = city_master_data['bathrooms_text'].replace(regex='([a-zA-Z])', value=0)

In [29]:
city_master_data['bathrooms_text'].unique()

array(['2', '1', '2.5', '1.5', '3', '3.5', '0', '4', '4.5', 0, '5', '9',
       '8', '6.5', '5.5', '7', '6', '10.5', '17', '7.5', '8.5', '12'],
      dtype=object)

In [30]:
#renaming the column name from "bathroom_text" to 'bathroom'
city_master_data.rename(columns={'bathrooms_text':'bathrooms'}, inplace=True)

In [31]:
#converting the column to folat type
city_master_data['bathrooms'] = city_master_data['bathrooms'].astype(float)

$~$

#### Checking the type of columns once again before removing missing fields

In [32]:
city_master_data.dtypes

id                             int64
host_is_superhost             object
host_total_listings_count    float64
neighbourhood                 object
latitude                     float64
longitude                    float64
property_type                 object
room_type                     object
accommodates                   int64
bathrooms                    float64
bedrooms                     float64
price                        float64
minimum_nights_avg_ntm       float64
maximum_nights_avg_ntm       float64
review_scores_rating         float64
review_scores_accuracy       float64
dtype: object

$~$

#### Formatting room_type column and remove "hotel room' type

In [33]:
#Checking all possible values of room_type
city_master_data['room_type'].unique()

array(['Entire home/apt', 'Private room', 'Hotel room', 'Shared room'],
      dtype=object)

In [34]:
len(city_master_data['room_type'])

10794

In [35]:
#### removing the "hotel room" type from the data set
city_master_data = city_master_data[city_master_data['room_type'] != 'Hotel room']

In [36]:
len(city_master_data['room_type'])

10785

In [37]:
#Checking all possible values of room_type
city_master_data['room_type'].unique()

array(['Entire home/apt', 'Private room', 'Shared room'], dtype=object)

$~$

#### Checking missing values in host_is_superhost column

In [38]:
#Displaying the rows when host_is_superhost column contains missing values
city_master_data[city_master_data['host_is_superhost'].isna()].head()

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy
912,4356661,NaN,NaN,NaN,30.25492,-97.74532,Entire rental unit,Entire home/apt,2,1.0,1.0,75.0,1.0,1125.0,0.00,NaN
1579,8214182,NaN,NaN,NaN,30.22839,-97.72529,Private room in rental unit,Private room,1,1.0,1.0,27.0,1.0,5.0,4.67,4.67
5571,32207144,NaN,NaN,"Austin, Texas, United States",30.27077,-97.74864,Entire condominium (condo),Entire home/apt,6,2.0,2.0,623.0,2.0,182.0,4.33,4.33
5572,32207608,NaN,NaN,"Austin, Texas, United States",30.27077,-97.74645,Entire residential home,Entire home/apt,4,1.0,1.0,356.0,2.0,182.0,NaN,NaN
5608,32338211,NaN,NaN,"Austin, Texas, United States",30.27077,-97.74696,Entire residential home,Entire home/apt,4,1.0,1.0,356.0,3.0,182.0,5.00,5.00

In [39]:
#Total number of rows having host_is_superhost column contains missing values
city_master_data[city_master_data['host_is_superhost'].isna()].shape

(48, 16)

In [40]:
#Dropping the rows having superhost column missing values
city_master_data.dropna(subset=['host_is_superhost'], inplace=True)

In [41]:
#Verifying the number of rowa after removal of missing values in host_is_superhost column
city_master_data.shape

(10737, 16)

$~$

#### Checking missing values in host_total_listings_count column

In [42]:
#Displaying the rows when host_total_listings_count column contains missing values
city_master_data[city_master_data['host_total_listings_count'].isna()].head()

Empty DataFrame
Columns: [id, host_is_superhost, host_total_listings_count, neighbourhood, latitude, longitude, property_type, room_type, accommodates, bathrooms, bedrooms, price, minimum_nights_avg_ntm, maximum_nights_avg_ntm, review_scores_rating, review_scores_accuracy]
Index: []

In [43]:
#Total number of rows having host_total_listings_count column contains missing values
city_master_data[city_master_data['host_total_listings_count'].isna()].shape

(0, 16)

In [44]:
#Dropping the rows having host_total_listings_count column missing values
city_master_data.dropna(subset=['host_total_listings_count'], inplace=True)

In [45]:
#Verifying the number of rowa after removal of missing values in host_total_listings_count column
city_master_data.shape

(10737, 16)

$~$

#### Checking missing values in neighbourhood column

In [46]:
# Displaying the rows when neighbourhood contains missing values
city_master_data[city_master_data['neighbourhood'].isna()].head()

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy
0,2265,t,3.0,NaN,30.27752,-97.71377,Entire residential home,Entire home/apt,4,2.0,2.0,200.0,7.0,180.0,4.68,4.74
1,5245,t,3.0,NaN,30.27614,-97.71320,Private room in residential home,Private room,2,1.0,1.0,114.0,30.0,90.0,4.57,4.80
6,8502,f,1.0,NaN,30.23466,-97.73682,Entire guest suite,Entire home/apt,2,1.0,1.0,44.0,9.3,90.0,4.60,4.54
8,22166,f,2.0,NaN,30.38794,-97.76358,Entire townhouse,Entire home/apt,4,2.5,2.0,153.0,30.0,365.0,4.80,5.00
15,69352,t,3.0,NaN,30.25811,-97.76368,Entire residential home,Entire home/apt,2,1.0,1.0,299.0,2.0,45.0,4.75,4.82

In [47]:
#Total number of rows having neighbourhood column contains missing values
city_master_data[city_master_data['neighbourhood'].isna()].shape

(4138, 16)

In [48]:
# Displaying the rows when neighbourhood does not contain missing values to take a decission with the missing value
city_master_data[~city_master_data['neighbourhood'].isna()].head()

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy
2,5456,t,1.0,"Austin, Texas, United States",30.26057,-97.73441,Entire guesthouse,Entire home/apt,3,1.0,1.0,104.0,2.0,90.0,4.83,4.87
3,5769,t,1.0,"Austin, Texas, United States",30.45697,-97.78422,Private room in residential home,Private room,2,1.0,1.0,39.0,1.0,14.0,4.90,4.90
4,6413,t,1.0,"Austin, Texas, United States",30.24885,-97.73587,Entire guesthouse,Entire home/apt,2,1.0,NaN,109.0,3.0,1125.0,4.97,4.99
5,6448,t,2.0,"Austin, Texas, United States",30.26034,-97.76487,Entire guesthouse,Entire home/apt,3,1.0,1.0,149.0,3.0,1125.0,4.98,4.96
7,21126,t,10.0,"Austin, Texas, United States",30.24417,-97.73988,Entire residential home,Entire home/apt,4,1.0,2.0,191.0,2.2,365.0,4.90,4.93

In [49]:
#Getting all values in neighbourhood column
#city_master_data['neighbourhood'].unique()

In [50]:
#Removal of rows containing missing values neighbourhood column
city_master_data.dropna(subset=['neighbourhood'], inplace=True)

In [51]:
#Verification of the data set after removal of missing values in neighbourhood column
city_master_data.shape

(6599, 16)

$~$

#### Checking missing values in bedrooms column

In [52]:
# Displaying the rows when bedrooms contains missing values
city_master_data[city_master_data['bedrooms'].isna()].head()

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy
4,6413,t,1.0,"Austin, Texas, United States",30.24885,-97.73587,Entire guesthouse,Entire home/apt,2,1.0,NaN,109.0,3.0,1125.0,4.97,4.99
36,78884,f,11.0,"Austin, Texas, United States",30.26126,-97.77358,Entire rental unit,Entire home/apt,2,1.0,NaN,118.0,2.1,1125.0,4.75,4.79
69,219168,f,1.0,"Austin, Texas, United States",30.24519,-97.74486,Entire rental unit,Entire home/apt,2,1.0,NaN,250.0,2.0,60.0,4.88,4.63
119,343889,t,1.0,"Austin, Texas, United States",30.27293,-97.72288,Entire rental unit,Entire home/apt,2,1.0,NaN,47.0,30.0,1125.0,4.79,4.92
264,801521,t,2.0,"Austin, Texas, United States",30.23457,-97.76150,Entire loft,Entire home/apt,5,1.0,NaN,104.0,2.0,1125.0,4.95,4.95

In [53]:
#Total number of rows having bedrooms column contains missing values
city_master_data[city_master_data['bedrooms'].isna()].shape

(457, 16)

In [54]:
#Removal of rows containing missing values bedrooms column
city_master_data.dropna(subset=['bedrooms'], inplace=True)

In [55]:
#Verification of the data set after removal of missing values in bedrooms column
city_master_data.shape

(6142, 16)

$~$

#### Checking missing values in review_scores_rating column

In [56]:
# Displaying the rows when review_scores_rating contains missing values
city_master_data[city_master_data['review_scores_rating'].isna()].head()

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy
29,77347,f,2.0,"Austin, Texas, United States",30.33877,-97.88200,Private room in residential home,Private room,2,1.0,1.0,104.0,2.0,14.0,NaN,NaN
40,80725,f,1.0,"Austin, Texas, United States",30.28251,-97.76874,Entire bungalow,Entire home/apt,5,2.0,3.0,150.0,30.0,1125.0,NaN,NaN
139,355328,f,1.0,"Austin, Texas, United States",30.23928,-97.77907,Entire residential home,Entire home/apt,2,1.0,1.0,100.0,1.0,1125.0,NaN,NaN
211,683558,f,1.0,"Austin, Texas, United States",30.27294,-97.79612,Entire residential home,Entire home/apt,8,3.0,3.0,2000.0,3.0,7.0,NaN,NaN
228,706950,f,1.0,"Austin, Texas, United States",30.28243,-97.77596,Entire residential home,Entire home/apt,8,3.5,4.0,2250.0,5.0,7.0,NaN,NaN

In [57]:
# Displaying the rows when review_scores_rating contains no missing values
city_master_data[~city_master_data['review_scores_rating'].isna()].head()

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy
2,5456,t,1.0,"Austin, Texas, United States",30.26057,-97.73441,Entire guesthouse,Entire home/apt,3,1.0,1.0,104.0,2.0,90.0,4.83,4.87
3,5769,t,1.0,"Austin, Texas, United States",30.45697,-97.78422,Private room in residential home,Private room,2,1.0,1.0,39.0,1.0,14.0,4.90,4.90
5,6448,t,2.0,"Austin, Texas, United States",30.26034,-97.76487,Entire guesthouse,Entire home/apt,3,1.0,1.0,149.0,3.0,1125.0,4.98,4.96
7,21126,t,10.0,"Austin, Texas, United States",30.24417,-97.73988,Entire residential home,Entire home/apt,4,1.0,2.0,191.0,2.2,365.0,4.90,4.93
9,22828,t,1.0,"Austin, Texas, United States",30.23614,-97.73225,Entire guesthouse,Entire home/apt,2,1.0,1.0,58.0,31.0,365.0,4.93,5.00

In [58]:
#Total number of rows having review_scores_rating column contains missing values
city_master_data[city_master_data['review_scores_rating'].isna()].shape

(884, 16)

In [59]:
#Removal of rows containing missing values review_scores_rating column
city_master_data.dropna(subset=['review_scores_rating'],inplace=True)

In [60]:
#Verification of the data set after removal of missing values in review_scores_rating column
city_master_data.shape

(5258, 16)

$~$

#### Checking missing values in review_scores_accuracy column

In [61]:
# Displaying the rows when review_scores_accuracy contains no missing values
city_master_data[~city_master_data['review_scores_accuracy'].isna()].head()

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy
2,5456,t,1.0,"Austin, Texas, United States",30.26057,-97.73441,Entire guesthouse,Entire home/apt,3,1.0,1.0,104.0,2.0,90.0,4.83,4.87
3,5769,t,1.0,"Austin, Texas, United States",30.45697,-97.78422,Private room in residential home,Private room,2,1.0,1.0,39.0,1.0,14.0,4.90,4.90
5,6448,t,2.0,"Austin, Texas, United States",30.26034,-97.76487,Entire guesthouse,Entire home/apt,3,1.0,1.0,149.0,3.0,1125.0,4.98,4.96
7,21126,t,10.0,"Austin, Texas, United States",30.24417,-97.73988,Entire residential home,Entire home/apt,4,1.0,2.0,191.0,2.2,365.0,4.90,4.93
9,22828,t,1.0,"Austin, Texas, United States",30.23614,-97.73225,Entire guesthouse,Entire home/apt,2,1.0,1.0,58.0,31.0,365.0,4.93,5.00

In [62]:
#Total number of rows having review_scores_accuracy column contains missing values
city_master_data[city_master_data['review_scores_accuracy'].isna()].shape

(44, 16)

In [63]:
#Removal of rows containing missing values review_scores_accuracy column
city_master_data.dropna(subset=['review_scores_accuracy'],inplace=True)

In [64]:
#Verification of the data set after removal of missing values in review_scores_accuracy column
city_master_data.shape

(5214, 16)

$~$

#### Checking missing values in minimum_nights_avg_ntm  column

In [65]:
# Displaying the rows when minimum_nights_avg_ntm contains missing values
city_master_data[city_master_data['minimum_nights_avg_ntm'].isna()].head()

Empty DataFrame
Columns: [id, host_is_superhost, host_total_listings_count, neighbourhood, latitude, longitude, property_type, room_type, accommodates, bathrooms, bedrooms, price, minimum_nights_avg_ntm, maximum_nights_avg_ntm, review_scores_rating, review_scores_accuracy]
Index: []

In [66]:
#Total number of rows having minimum_nights_avg_ntm column contains missing values
city_master_data[city_master_data['minimum_nights_avg_ntm'].isna()].shape

(0, 16)

In [67]:
#Removal of rows containing missing values minimum_nights_avg_ntm column
city_master_data.dropna(subset=['minimum_nights_avg_ntm'],inplace=True)

In [68]:
#Verification of the data set after removal of missing values in minimum_nights_avg_ntm column
city_master_data.shape

(5214, 16)

$~$

#### Checking missing values in maximum_nights_avg_ntm column

In [69]:
# Displaying the rows when maximum_nights_avg_ntm contains missing values
city_master_data[city_master_data['maximum_nights_avg_ntm'].isna()].head()

Empty DataFrame
Columns: [id, host_is_superhost, host_total_listings_count, neighbourhood, latitude, longitude, property_type, room_type, accommodates, bathrooms, bedrooms, price, minimum_nights_avg_ntm, maximum_nights_avg_ntm, review_scores_rating, review_scores_accuracy]
Index: []

In [70]:
#Total number of rows having maximum_nights_avg_ntm column contains missing values
city_master_data[city_master_data['maximum_nights_avg_ntm'].isna()].shape

(0, 16)

In [71]:
#Removal of rows containing missing values maximum_nights_avg_ntm column
city_master_data.dropna(subset=['maximum_nights_avg_ntm'],inplace=True)

In [72]:
#Verification of the data set after removal of missing values in minimum_nights_avg_ntm column
city_master_data.shape

(5214, 16)

$~$

#### Final check on missing values as well as count on listing data set

In [73]:
city_master_data.isnull().sum()

id                           0
host_is_superhost            0
host_total_listings_count    0
neighbourhood                0
latitude                     0
longitude                    0
property_type                0
room_type                    0
accommodates                 0
bathrooms                    0
bedrooms                     0
price                        0
minimum_nights_avg_ntm       0
maximum_nights_avg_ntm       0
review_scores_rating         0
review_scores_accuracy       0
dtype: int64

In [74]:
city_master_data.shape

(5214, 16)

$~$

## City Calendar Data set

#### Reading Calendar Data Set

In [75]:
#Reading Sep Calendar Data set
#city_master_calendar_data = pd.read_csv("dallas_calendar_sep.csv")
#city_master_calendar_data = pd.read_csv("newyork_calendar_sep.csv")
#city_master_calendar_data = pd.read_csv("sfo_calendar.csv")
#city_master_calendar_data = pd.read_csv("la_calendar.csv")
#city_master_calendar_data = pd.read_csv("san_diego_calendar.csv")
#city_master_calendar_data = pd.read_csv("newark_calendar.csv")
#city_master_calendar_data = pd.read_csv("chicago_calendar.csv")
#city_master_calendar_data = pd.read_csv("columbus_calendar.csv")
#city_master_calendar_data = pd.read_csv("denver_calendar.csv")
#city_master_calendar_data = pd.read_csv("seattle_calendar.csv")
#city_master_calendar_data = pd.read_csv("portland_calendar.csv")
#city_master_calendar_data = pd.read_csv("boston_calendar.csv")
city_master_calendar_data = pd.read_csv("austin_calendar.csv")

In [76]:
city_master_calendar_data

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,343462,2021-09-15,f,$99.00,$99.00,1.0,14.0
1,342039,2021-09-15,t,$140.00,$140.00,2.0,60.0
2,342039,2021-09-16,f,$140.00,$140.00,3.0,60.0
3,342039,2021-09-17,f,$140.00,$140.00,3.0,60.0
4,342039,2021-09-18,f,$140.00,$140.00,3.0,60.0
...,...,...,...,...,...,...,...
3944918,51991078,2022-09-10,t,$220.00,$220.00,2.0,1125.0
3944919,51991078,2022-09-11,t,$156.00,$156.00,2.0,1125.0
3944920,51991078,2022-09-12,t,$133.00,$133.00,2.0,1125.0
3944921,51991078,2022-09-13,t,$130.00,$130.00,2.0,1125.0
3944922,51991078,2022-09-14,t,$131.00,$131.00,2.0,1125.0

In [77]:
#Taking a back up the master data set
city_master_calendar_data_copy = city_master_calendar_data.copy()

In [78]:
#Renaming listing_id column as id
city_master_calendar_data.rename(columns={'listing_id':'id'}, inplace=True)

In [79]:
#Renaming price column as income
city_master_calendar_data.rename(columns={'price':'income'}, inplace=True)

In [80]:
city_master_calendar_data.dtypes

id                  int64
date               object
available          object
income             object
adjusted_price     object
minimum_nights    float64
maximum_nights    float64
dtype: object

$~$

#### Keeping the records only for October month

In [81]:
city_master_calendar_data = city_master_calendar_data[(city_master_calendar_data['date'] > '2021-09-30') & \
                               (city_master_calendar_data['date'] < '2021-11-01')]

In [82]:
city_master_calendar_data

,id,date,available,income,adjusted_price,minimum_nights,maximum_nights
17,342039,2021-10-01,f,$200.00,$200.00,3.0,60.0
18,342039,2021-10-02,f,$200.00,$200.00,3.0,60.0
19,342039,2021-10-03,f,$200.00,$200.00,2.0,60.0
20,342039,2021-10-04,t,$200.00,$200.00,2.0,60.0
21,342039,2021-10-05,t,$200.00,$200.00,2.0,60.0
...,...,...,...,...,...,...,...
3944600,51991078,2021-10-27,t,$119.00,$119.00,2.0,1125.0
3944601,51991078,2021-10-28,t,$141.00,$141.00,2.0,1125.0
3944602,51991078,2021-10-29,t,$194.00,$194.00,2.0,1125.0
3944603,51991078,2021-10-30,t,$198.00,$198.00,2.0,1125.0
3944604,51991078,2021-10-31,t,$141.00,$141.00,2.0,1125.0

$~$

#### Formatting income column

In [83]:
#Removing $ and , from the price columnvalues
city_master_calendar_data['income'].replace('\$','', regex=True, inplace=True)
city_master_calendar_data['income'].replace('\,','', regex=True, inplace=True)
#city_master_calendar_data['income'] = city_master_calendar_data['income'].str.replace(r'$', '')
#city_master_calendar_data['income'] = city_master_calendar_data['income'].str.replace(r',', '')

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4563: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [84]:
#Converting price into float type
city_master_calendar_data['income'] = city_master_calendar_data['income'].astype(float)

<ipython-input-84-3742c08aed76>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  city_master_calendar_data['income'] = city_master_calendar_data['income'].astype(float)

In [85]:
city_master_calendar_data

,id,date,available,income,adjusted_price,minimum_nights,maximum_nights
17,342039,2021-10-01,f,200.0,$200.00,3.0,60.0
18,342039,2021-10-02,f,200.0,$200.00,3.0,60.0
19,342039,2021-10-03,f,200.0,$200.00,2.0,60.0
20,342039,2021-10-04,t,200.0,$200.00,2.0,60.0
21,342039,2021-10-05,t,200.0,$200.00,2.0,60.0
...,...,...,...,...,...,...,...
3944600,51991078,2021-10-27,t,119.0,$119.00,2.0,1125.0
3944601,51991078,2021-10-28,t,141.0,$141.00,2.0,1125.0
3944602,51991078,2021-10-29,t,194.0,$194.00,2.0,1125.0
3944603,51991078,2021-10-30,t,198.0,$198.00,2.0,1125.0
3944604,51991078,2021-10-31,t,141.0,$141.00,2.0,1125.0

$~$

#### Removal of unwanted columns from Calendar Data set

In [86]:
#Removal of columns
calendar_column_remove = ['date','adjusted_price','minimum_nights','maximum_nights']
city_master_calendar_data.drop(calendar_column_remove, axis=1,inplace=True)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [87]:
city_master_calendar_data

               id available  income
17         342039         f   200.0
18         342039         f   200.0
19         342039         f   200.0
20         342039         t   200.0
21         342039         t   200.0
...           ...       ...     ...
3944600  51991078         t   119.0
3944601  51991078         t   141.0
3944602  51991078         t   194.0
3944603  51991078         t   198.0
3944604  51991078         t   141.0

[335048 rows x 3 columns]

In [88]:
city_master_calendar_data.head()

        id available  income
17  342039         f   200.0
18  342039         f   200.0
19  342039         f   200.0
20  342039         t   200.0
21  342039         t   200.0

$~$

#### Removal of rows containg missing values in income column

In [89]:
#Checking for Null Values
city_master_calendar_data.isnull().sum()

id            0
available     0
income       31
dtype: int64

In [90]:
#Displaying all the misisng values rows
city_master_calendar_data[city_master_calendar_data.isna().any(axis=1)]

               id available  income
1378128  20945127         f     NaN
1378129  20945127         f     NaN
1378130  20945127         f     NaN
1378131  20945127         f     NaN
1378132  20945127         f     NaN
1378133  20945127         f     NaN
1378134  20945127         f     NaN
1378135  20945127         f     NaN
1378136  20945127         f     NaN
1378137  20945127         f     NaN
1378138  20945127         f     NaN
1378139  20945127         f     NaN
1378140  20945127         f     NaN
1378141  20945127         f     NaN
1378142  20945127         f     NaN
1378143  20945127         f     NaN
1378144  20945127         f     NaN
1378145  20945127         f     NaN
1378146  20945127         f     NaN
1378147  20945127         f     NaN
1378148  20945127         f     NaN
1378149  20945127         f     NaN
1378229  20945127         f     NaN
1378230  20945127         f     NaN
1378231  20945127         f     NaN
1378232  20945127         f     NaN
1378233  20945127         f     NaN
1378234  20945127         f     NaN
1378235  20945127         f     NaN
1378236  20945127         f     NaN
1378237  20945127         f     NaN

In [91]:
#Dropping the rows with missing values
city_master_calendar_data.dropna(axis=0, inplace=True)

<ipython-input-91-a6946eb95971>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  city_master_calendar_data.dropna(axis=0, inplace=True)

In [92]:
city_master_calendar_data.shape

(335017, 3)

In [93]:
#Rechecking the Null values again
city_master_calendar_data.isnull().sum()

id           0
available    0
income       0
dtype: int64

$~$

#### Check which rental have less than 31 days record

In [94]:
city_master_calendar_data.shape

(335017, 3)

In [95]:
valid_id=city_master_calendar_data['id'].value_counts().to_dict()

In [96]:
city_master_calendar_data['count'] = city_master_calendar_data['id'].map(valid_id)
city_master_calendar_data.head()

<ipython-input-96-76f5d35be195>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  city_master_calendar_data['count'] = city_master_calendar_data['id'].map(valid_id)

        id available  income  count
17  342039         f   200.0     31
18  342039         f   200.0     31
19  342039         f   200.0     31
20  342039         t   200.0     31
21  342039         t   200.0     31

In [97]:
mask=city_master_calendar_data['count']<31
omit_row=city_master_calendar_data[mask]
omit_row  #cool! all rental property has 31

Empty DataFrame
Columns: [id, available, income, count]
Index: []

In [98]:
#if any rental is without 31 rows, throw away
city_master_calendar_data=city_master_calendar_data[~mask]
city_master_calendar_data.shape

(335017, 4)

In [99]:
#Delet the 'count' column
city_master_calendar_data.drop('count',axis=1,inplace=True)
city_master_calendar_data.head()

        id available  income
17  342039         f   200.0
18  342039         f   200.0
19  342039         f   200.0
20  342039         t   200.0
21  342039         t   200.0

$~$

#### Filtering the data set only for available records with 'f'

In [100]:
#### Filtering the data set only for available records with f that means it is already being reserved in the past
city_master_calendar_data = city_master_calendar_data[city_master_calendar_data['available'] == 'f']

In [101]:
city_master_calendar_data.shape

(237039, 3)

In [102]:
#Just verifying that data set only contains data with available 'f'
city_master_calendar_data['available'].unique()

array(['f'], dtype=object)

In [103]:
city_master_calendar_data

               id available  income
17         342039         f   200.0
18         342039         f   200.0
19         342039         f   200.0
23         342039         f   200.0
24         342039         f   225.0
...           ...       ...     ...
3944590  51991078         f   149.0
3944594  51991078         f   185.0
3944595  51991078         f   243.0
3944596  51991078         f   250.0
3944597  51991078         f   186.0

[237039 rows x 3 columns]

In [104]:
city_master_calendar_data.dtypes

id             int64
available     object
income       float64
dtype: object

$~$

#### Final check on missing value and count on calendar data set

In [105]:
city_master_calendar_data.isnull().sum()

id           0
available    0
income       0
dtype: int64

In [106]:
city_master_calendar_data.shape

(237039, 3)

$~$

## Merging City Listing and Calendar Data set

In [107]:
#City Listing Data set
city_master_data.head()

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy
2,5456,t,1.0,"Austin, Texas, United States",30.26057,-97.73441,Entire guesthouse,Entire home/apt,3,1.0,1.0,104.0,2.0,90.0,4.83,4.87
3,5769,t,1.0,"Austin, Texas, United States",30.45697,-97.78422,Private room in residential home,Private room,2,1.0,1.0,39.0,1.0,14.0,4.90,4.90
5,6448,t,2.0,"Austin, Texas, United States",30.26034,-97.76487,Entire guesthouse,Entire home/apt,3,1.0,1.0,149.0,3.0,1125.0,4.98,4.96
7,21126,t,10.0,"Austin, Texas, United States",30.24417,-97.73988,Entire residential home,Entire home/apt,4,1.0,2.0,191.0,2.2,365.0,4.90,4.93
9,22828,t,1.0,"Austin, Texas, United States",30.23614,-97.73225,Entire guesthouse,Entire home/apt,2,1.0,1.0,58.0,31.0,365.0,4.93,5.00

In [108]:
#City Calendar Data set
city_master_calendar_data.head()

        id available  income
17  342039         f   200.0
18  342039         f   200.0
19  342039         f   200.0
23  342039         f   200.0
24  342039         f   225.0

In [109]:
#Merging the listing data set and calendar dara set and also summing up the price for respective ids
city_listing_calendar_temp = pd.concat([city_master_data, city_master_calendar_data]).groupby('id')\
                            ['income'].sum().reset_index()

In [110]:
#Then LEFT merging with listing data set to contain only the ids present in listing data set
city_listing_calendar_data = pd.merge(city_master_data, city_listing_calendar_temp, how='left', on=['id'])

$~$

#### Final cleaned merged data set

In [111]:
city_listing_calendar_data

,id,host_is_superhost,host_total_listings_count,neighbourhood,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy,income
0,5456,t,1.0,"Austin, Texas, United States",30.26057,-97.73441,Entire guesthouse,Entire home/apt,3,1.0,1.0,104.0,2.0,90.0,4.83,4.87,2895.0
1,5769,t,1.0,"Austin, Texas, United States",30.45697,-97.78422,Private room in residential home,Private room,2,1.0,1.0,39.0,1.0,14.0,4.90,4.90,1238.0
2,6448,t,2.0,"Austin, Texas, United States",30.26034,-97.76487,Entire guesthouse,Entire home/apt,3,1.0,1.0,149.0,3.0,1125.0,4.98,4.96,3115.0
3,21126,t,10.0,"Austin, Texas, United States",30.24417,-97.73988,Entire residential home,Entire home/apt,4,1.0,2.0,191.0,2.2,365.0,4.90,4.93,5292.0
4,22828,t,1.0,"Austin, Texas, United States",30.23614,-97.73225,Entire guesthouse,Entire home/apt,2,1.0,1.0,58.0,31.0,365.0,4.93,5.00,1798.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5209,51990565,f,0.0,"Austin, Texas, United States",30.19706,-97.72871,Entire residential home,Entire home/apt,12,2.5,3.0,152.0,2.0,27.0,5.00,5.00,2591.0
5210,52012763,f,3.0,"Austin, Texas, United States",30.24632,-97.73029,Entire rental unit,Entire home/apt,3,1.0,1.0,214.0,1.0,1125.0,5.00,5.00,1600.0
5211,52052818,f,0.0,"Austin, Texas, United States",30.37974,-97.95726,Entire guest suite,Entire home/apt,4,1.0,1.0,97.0,1.0,1125.0,5.00,5.00,340.0
5212,52110039,t,0.0,"Austin, Texas, United States",30.25220,-97.72298,Entire residential home,Entire home/apt,7,2.0,3.0,426.0,2.0,1125.0,5.00,5.00,1356.0
5213,52112461,f,0.0,"Austin, Texas, United States",30.31757,-97.72310,Entire residential home,Entire home/apt,4,1.0,2.0,140.0,1.3,14.0,5.00,5.00,700.0

In [112]:
city_listing_calendar_data.shape

(5214, 17)

In [113]:
#city_listing_calendar_data.to_csv('dallas_merge.csv')
#city_listing_calendar_data.to_csv('newyork_merge.csv')
#city_listing_calendar_data.to_csv('sfo_merge.csv')
#city_listing_calendar_data.to_csv('la_merge.csv')
#city_listing_calendar_data.to_csv('san_diego_merge.csv')
#city_listing_calendar_data.to_csv('newark_merge.csv')
#city_listing_calendar_data.to_csv('chicago_merge.csv')
#city_listing_calendar_data.to_csv('columbus_merge.csv')
#city_listing_calendar_data.to_csv('denver_merge.csv')
#city_listing_calendar_data.to_csv('seattle_merge.csv')
#city_listing_calendar_data.to_csv('portland_merge.csv')
#city_listing_calendar_data.to_csv('boston_merge.csv')
city_listing_calendar_data.to_csv('austin_merge.csv')